version: "3.7"
services:
  frontend:
    build: 
      context: ./
      dockerfile: Dockerfile
    ports:
      - "80:80"
      # - "5000:5000"
    network_mode: host
    environment: 
      # USE PRIVATE IP NAT/PROXY INSTANCE, SEND REQUEST WITHIN VPC
      - proxyUrl=http://10.0.7.252
      # - proxyUrl=http://host.docker.internal
      - ascendaUrl=http://ascenda-load-balancer-1751800571.us-east-1.elb.amazonaws.com